version: 2
project_name: glass
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: glass
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      #- darwin
      #- linux
    goarch:
      - amd64
      - 386
    hooks:
      post: upx --lzma '{{ .Path }}'
archives:
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - sample.bat
release:
  prerelease: auto
changelog:
  filters:
    exclude:
    - '^test:'
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)!]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)!]*:+.*$"
      order: 1
    - title: 'Others'
      order: 999