# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/shu-go/glass

    environment:
      - GOPATH: /home/circleci/go

    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -u  github.com/Songmu/goxz/cmd/goxz  github.com/tcnksm/ghr
      - run: goxz -pv $(git describe)  -os "windows"  -arch="386 amd64" -build-ldflags "-s -w -X main.Version=$(git describe)" -include サンプル_動画中毒.bat
      - run: ghr -t $GITHUB_TOKEN  -u shu-go  --replace $(git describe)  goxz/

workflows:
  version: 2
  test-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
